### ISSUE TITLE
Login is unavailable

### ISSUE THREAD

**Issue by BlueWhaleYT** [codedamn/codedamn#2]
I can register an account in codedamn of broswer version and login.
However, I cannot login in application. It did a loading circle after I clicked login button then nothing happened.

It didn't take me to the main core.

Thanks.

**Comment by mehulmpt** [comment]
A similar problem was found and patched yesterday. What is your registered username on codedamn?

**Comment by BlueWhaleYT** [comment]
thats exactly same with my github username

**Comment by mehulmpt** [comment]
I've checked on my side. Things look good. Although codedamn makes use of cache busting, still, would you mind just clearing your cookies and cache for codedamn.com and try once more? If the problem is still there, let me know so that we can resolve it.

**Comment by BlueWhaleYT** [comment]
yes it is still.

**Comment by mehulmpt** [comment]
Unfortunately, I'm unable to see any reports of any crash on Sentry, and neither on the backend. So you would need to help me out here. Can you record a small video of you logging in codedamn - with possibly the DevTools opened? Please see this little example of what I'm expecting you to do:

![Process](https://user-images.githubusercontent.com/10388889/81028271-444b8b80-8e9e-11ea-98d1-339bd65fe289.gif)

You can mail me the video here: mehulmpt@gmail.com

**Comment by BlueWhaleYT** [comment]
Check it.

**Comment by mehulmpt** [comment]
Oh! I get it now. The **mobile app** isn't working. I'm sorry I'm aware about this. I unpublished the Android and iOS version from their stores a week ago - this is because a significant API change is undergoing and I cannot support the previous versions. I would bring back the apps in about 4 days again with complete working support. Till then, please stick to the browser version of the app :)

Thanks for sharing the video!

**Comment by BlueWhaleYT** [comment]
Ok, I am staying tuned.
